project:
  type: website
  output-dir: docs

website:
  title: "The Brewery Project"
  favicon: images/beer-mug-icon.png
  navbar:
    left:
      - href: introduction.qmd
        text: "Introduction"
      - href: data_exploration.qmd
        text: "Data Exploration"
      - href: models_implemented.qmd
        text: "Models Implemented"
      - href: conclusion.qmd
        text: "Conclusion"
    right:
      - icon: github
        href: https://github.com/The-Brewery-Project/The-Brewery-Project

format:
  html:
    email-obfuscation: javascript
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
    citations-hover: true
    code-link: true
    code-fold: true
    theme: cosmo
    css: styles.css
    toc: true
